ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.confraajuda.ApplicationKt.module ]
    }
}

confrapix {
    token = ""
    token = ${?CONFRAPIX_TOKEN}
    apiUrl = "https://api.confrapix.com.br/api"
    mockMode = true
    mockMode = ${?CONFRAPIX_MOCK_MODE}
}
